In [1]:
 import pandas as pd
 import numpy as np
 import seaborn as sns
 import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/content/drive/MyDrive/train.csv')

In [4]:
df = df.sample(30000)

In [5]:
df.sample(5)

,id,qid1,qid2,question1,question2,is_duplicate
132374,132374,211972,211973,How are noble gases stable?,What are noble gases?,0
170382,170382,182956,9708,Which is the best book for python?,What are the best C++ books?,0
286271,286271,406814,406815,Terminator (creative franchise): How does Skyn...,Terminator (creative franchise): Could Cameron...,0
225531,225531,333890,333891,Which is the best nationalised bank In India?,Who nationalises banks in India?,0
47732,47732,85195,85196,How do you convince a conservative Muslim fami...,Is the court marriage of a Hindu boy and Musli...,0

In [6]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import hstack

ques_df = df[['question1', 'question2']]

cv = CountVectorizer(max_features=3000)
cv.fit(list(ques_df['question1']) + list(ques_df['question2']))

q1_vec = cv.transform(ques_df['question1'])
q2_vec = cv.transform(ques_df['question2'])

X = hstack([q1_vec, q2_vec])
temp_df = pd.DataFrame(X.toarray(), index=ques_df.index)

In [8]:
temp_df.shape

(30000, 6000)

In [9]:
temp_df['is_duplicate'] = df['is_duplicate']

In [10]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,5991,5992,5993,5994,5995,5996,5997,5998,5999,is_duplicate
124975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71659,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221795,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
157843,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,1,0,0,0,0,0

In [11]:
X = temp_df.iloc[:, :-1]
Y = temp_df.iloc[:, -1]

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, random_state=2)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
y_pred = rf.predict(X_test)

In [13]:
accuracy_score(Y_test,y_pred)

0.7361666666666666

In [14]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,Y_train)
y_pred = xgb.predict(X_test)

In [16]:
accuracy_score(Y_test,y_pred)

0.7295